---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-dpu-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: dpu-cni
spec:
  selector:
    matchLabels:
      name: dpu-cni
  template:
    metadata:
      labels:
        name: dpu-cni
        tier: node
        app: dpu-cni
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-dpu-cni
        image: quay.io/wizhao/dpucni:0.0.6
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
