---
apiVersion: v1
kind: Namespace
metadata:
  name: dpu-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpu-operator-daemons
  namespace: dpu-operator
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: host-daemon
  namespace: dpu-operator
spec:
  selector:
    matchLabels:
      app: host-daemon
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: host-daemon
        component: network
        type: infra
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists
      serviceAccountName: dpu-operator-daemons
      priorityClassName: "system-node-critical"
      containers:
      - name: host-daemon
        image: quay.io/wizhao/grpc_server:0.0.1
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: host
            mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: dpu-daemon
  namespace: dpu-operator
spec:
  selector:
    matchLabels:
      app: dpu-daemon
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: dpu-daemon
        component: network
        type: infra
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists
      serviceAccountName: dpu-operator-daemons
      priorityClassName: "system-node-critical"
      containers:
      - name: dpu-daemon
        image: quay.io/wizhao/grpc_client:0.0.1
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: host
            mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
