---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-pod
  annotations:
     k8s.v1.cni.cncf.io/networks: dpucni-conf
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
      runAsNonRoot: true
  containers:
  - name: my-pod
    image: quay.io/wizhao/ft-base-image:0.9
    command:
      - "/sbin/init"
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 999
      capabilities:
        drop:
          - ALL
