apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dpusriovcni-conf
  annotations:
        k8s.v1.cni.cncf.io/resourceName: intel.com/marvell_sriov
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "dpusriovcni",
      "type": "sriov",
      "ipam": {
          "type": "host-local",
          "subnet": "10.1.2.0/24"
      }
    }'
